name: Workflow + Docker + Terraform

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker (already pre-installed in ubuntu-latest)
      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run Docker container
        run: docker run --rm my-app

      # 3. Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # 6. Save Terraform output to file
      - name: Save actual file content to output.txt
        run: |
          file_path=$(terraform output -raw file_path)
          cat "$file_path" > output.txt


      # 7. Upload output.txt as artifact
      - name: Upload Terraform Output
        uses: actions/upload-artifact@v4
        with:
          name: terraform-output
          path: output.txt
